#include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.inject.dart"
    - "**/*.inject.summary"
    - "**/*.config.dart"
    - "**/*.iconfig.dart"
  enable-experiment:
    - extension-methods
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error


linter:
  rules:
    prefer_const_constructors: false
    await_only_futures: true