name: tus_class
description: A front-end APP for TUS CLASS. This Project is only for Tokyo University of Science students.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.3+13

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.12.0

  flutter_secure_storage: ^3.3.4
  shared_preferences: ^0.5.12
  dio_cookie_manager: ^1.0.0
  flutter_neumorphic: ^3.0.2
  html_unescape: ^1.0.2
  package_info: ^0.4.3
  charts_flutter: ^0.9.0
  store_redirect: ^1.0.2
  path_provider: ^1.6.18
  injectable: ^1.0.4
  flutter_svg: ^0.19.0
  flutter_bloc: ^6.0.5
  url_launcher: ^5.7.2
  cookie_jar: ^1.0.1
  open_file: ^3.0.1
  equatable: ^1.2.5
  shimmer: ^1.1.1
  sembast: ^2.4.7+7
  get_it: ^4.0.4
  dartz: ^0.9.1
  mutex: ^1.1.0
  yaml: ^2.2.1
  dio: ^3.0.10
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
  mockito: ^4.1.2
  freezed: ^0.12.1
  build_runner: ^1.10.0
  json_serializable: ^3.5.0
  injectable_generator: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Localizations
    - assets/locale/en.json
    - assets/locale/ja.json
    - assets/locale/zh.json

    # Illustration
    - assets/illustration/space/milky-way.svg
    - assets/illustration/space/moon.svg
    - assets/illustration/space/planet-earth-2.svg
    - assets/illustration/space/planet-earth-3.svg
    - assets/illustration/space/moon-rover.svg
    - assets/illustration/space/space-ship.svg
    - assets/illustration/space/space-ship-3.svg
    - assets/illustration/space/solar-system.svg
    - assets/illustration/space/spaceship-1.svg
    - assets/illustration/space/artificial-gravity-modulo.svg
    - assets/illustration/space/satellite-dish.svg
    - assets/illustration/space/lunar-module.svg
    - assets/illustration/space/venus.svg
    - assets/illustration/space/ufo.svg
    - assets/illustration/space/ursa-major.svg
    - assets/illustration/space/space-ship-6.svg

    - assets/illustration/user-experience/036-usability.svg
    - assets/illustration/user-experience/017-unit.svg

    - assets/illustration/files/3ds.svg
    - assets/illustration/files/aac.svg
    - assets/illustration/files/ai.svg
    - assets/illustration/files/avi.svg
    - assets/illustration/files/bmp.svg
    - assets/illustration/files/cad.svg
    - assets/illustration/files/cdr.svg
    - assets/illustration/files/css.svg
    - assets/illustration/files/dat.svg
    - assets/illustration/files/dll.svg
    - assets/illustration/files/dmg.svg
    - assets/illustration/files/doc.svg
    - assets/illustration/files/eps.svg
    - assets/illustration/files/fla.svg
    - assets/illustration/files/flv.svg
    - assets/illustration/files/gif.svg
    - assets/illustration/files/html.svg
    - assets/illustration/files/indd.svg
    - assets/illustration/files/iso.svg
    - assets/illustration/files/jpg.svg
    - assets/illustration/files/js.svg
    - assets/illustration/files/midi.svg
    - assets/illustration/files/mov.svg
    - assets/illustration/files/mp3.svg
    - assets/illustration/files/mpg.svg
    - assets/illustration/files/pdf.svg
    - assets/illustration/files/php.svg
    - assets/illustration/files/png.svg
    - assets/illustration/files/ppt.svg
    - assets/illustration/files/ps.svg
    - assets/illustration/files/psd.svg
    - assets/illustration/files/raw.svg
    - assets/illustration/files/sql.svg
    - assets/illustration/files/svg.svg
    - assets/illustration/files/tif.svg
    - assets/illustration/files/txt.svg
    - assets/illustration/files/wmv.svg
    - assets/illustration/files/xls.svg
    - assets/illustration/files/xml.svg
    - assets/illustration/files/zip.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
