name: tus_class
description: A front-end APP for TUS CLASS. This Project is only for Tokyo University of Science students.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.0+15
publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.3
  flutter_secure_storage: ^5.0.0-beta.5 #Windows support in 5.0.0-beta
  shared_preferences: ^2.0.8
  dio_cookie_manager: ^2.0.0
  flutter_neumorphic: #^3.1.0
    git:
      url: https://github.com/tsvillain/Flutter-Neumorphic.git #flutter^2.5におけるconflict対策
  html_unescape: ^2.0.0
  package_info_plus: ^1.0.6 #changed from package_info in order to support Windows
  charts_flutter: #^0.11.0
    git:
      url: git://github.com/google/charts.git #body1 error対策
      path: charts_flutter
  store_redirect: ^2.0.0 #no support for Windows
  path_provider: ^2.0.5
  injectable: ^1.5.0
  flutter_svg: ^0.22.0
  flutter_bloc: ^7.3.0
  url_launcher: ^6.0.12
  cookie_jar: ^3.0.1
  open_file: ^3.2.1 #no support for Windows
  equatable: ^2.0.3
  shimmer: ^2.0.0
  sembast: ^3.1.1
  get_it: ^7.2.0
  dartz: ^0.10.0
  mutex: ^3.0.0
  yaml: ^3.1.0
  dio: ^4.0.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2
  mockito: ^5.0.16
  freezed: ^0.14.5
  build_runner: ^2.1.2
  json_serializable: ^5.0.2
  injectable_generator: ^1.5.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Localizations
    - assets/locale/en.json
    - assets/locale/ja.json
    - assets/locale/zh.json

    # Illustration
    - assets/illustration/space/milky-way.svg
    - assets/illustration/space/moon.svg
    - assets/illustration/space/planet-earth-2.svg
    - assets/illustration/space/planet-earth-3.svg
    - assets/illustration/space/moon-rover.svg
    - assets/illustration/space/space-ship.svg
    - assets/illustration/space/space-ship-3.svg
    - assets/illustration/space/solar-system.svg
    - assets/illustration/space/spaceship-1.svg
    - assets/illustration/space/artificial-gravity-modulo.svg
    - assets/illustration/space/satellite-dish.svg
    - assets/illustration/space/lunar-module.svg
    - assets/illustration/space/venus.svg
    - assets/illustration/space/ufo.svg
    - assets/illustration/space/ursa-major.svg
    - assets/illustration/space/space-ship-6.svg

    - assets/illustration/user-experience/036-usability.svg
    - assets/illustration/user-experience/017-unit.svg

    - assets/illustration/files/3ds.svg
    - assets/illustration/files/aac.svg
    - assets/illustration/files/ai.svg
    - assets/illustration/files/avi.svg
    - assets/illustration/files/bmp.svg
    - assets/illustration/files/cad.svg
    - assets/illustration/files/cdr.svg
    - assets/illustration/files/css.svg
    - assets/illustration/files/dat.svg
    - assets/illustration/files/dll.svg
    - assets/illustration/files/dmg.svg
    - assets/illustration/files/doc.svg
    - assets/illustration/files/eps.svg
    - assets/illustration/files/fla.svg
    - assets/illustration/files/flv.svg
    - assets/illustration/files/gif.svg
    - assets/illustration/files/html.svg
    - assets/illustration/files/indd.svg
    - assets/illustration/files/iso.svg
    - assets/illustration/files/jpg.svg
    - assets/illustration/files/js.svg
    - assets/illustration/files/midi.svg
    - assets/illustration/files/mov.svg
    - assets/illustration/files/mp3.svg
    - assets/illustration/files/mpg.svg
    - assets/illustration/files/pdf.svg
    - assets/illustration/files/php.svg
    - assets/illustration/files/png.svg
    - assets/illustration/files/ppt.svg
    - assets/illustration/files/ps.svg
    - assets/illustration/files/psd.svg
    - assets/illustration/files/raw.svg
    - assets/illustration/files/sql.svg
    - assets/illustration/files/svg.svg
    - assets/illustration/files/tif.svg
    - assets/illustration/files/txt.svg
    - assets/illustration/files/wmv.svg
    - assets/illustration/files/xls.svg
    - assets/illustration/files/xml.svg
    - assets/illustration/files/zip.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
