name: Build

on:
  push:
    tags:
      - 'v*.*.*\+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.2'
          channel: 'stable'
      - run: flutter pub get
      - run: |
          find ./lib -name "*.dart" \
            -not -name "*.g.dart" \
            -not -name "*.freezed.dart" \
            -not -name "*.*config.dart" \
            -exec flutter format \
            --set-exit-if-changed \
            --line-length 800 {} \;
      - run: flutter analyze .
      - name: Secrets
        run: |
          echo $KEY_PROPERTIES | base64 -d > ./android/key.properties
          echo $JKS_KEY | base64 -d > ./key.jks
          echo $SERVICE_ACCOUNT_JSON | base64 -d > ./service_account.json
        env:
          JKS_KEY: ${{ secrets.JKS_KEY }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      - run: flutter build appbundle
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false
      # - name: Upload Release Asset
      #   id: upload-release-asset 
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./build/app/outputs/bundle/release/app-release.aab
      #     asset_name: app-release.aab
      #     asset_content_type: application/octet-stream
          # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-aab
          path: ./build/app/outputs/bundle/release/app-release.aab
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ./service_account.json
          packageName: com.huhu.tusclass
          releaseFile: ./build/app/outputs/bundle/release/app-release.aab
          track: beta
          userFraction: 1.0
          whatsNewDirectory: whatsnew
